### ISSUE TITLE
缺少ToJson代码

### ISSUE THREAD

**Issue by oneces** [mp2930696631/visualization-neo4j-using-java#1]
为了赚点csdn积分，煞费苦心，文件单独上传，目录结构打乱。各种文件都下全了，积分都给了，你到时代码给全啊。

**Comment by mp2930696631** [comment]
import java.io.FileNotFoundException;

import java.io.FileOutputStream;

import java.io.IOException;



public class ToJson {



    private String json = "";



    //将格式化节点数据和关系数据拼凑成完整的json数据

    public ToJson(StringBuffer relationNodesBuffer, StringBuffer relationBuffer){

        StringBuffer result = new StringBuffer("");

        result.append("{");

        result.append(relationNodesBuffer);

        result.append(",");

        result.append("\n");//换行

        result.append(relationBuffer);

        result.append("}");



        json = result.toString();



    }



    //将json数据写入文件

    public void writeJson(){

        try {

            FileOutputStream fileOutputStream = new FileOutputStream("D:\\Idea\\Workspace\\TestTraining\\web\\data.json");

            fileOutputStream.write(json.getBytes());

            fileOutputStream.close();

        } catch (FileNotFoundException e) {

            e.printStackTrace();

        } catch (IOException e) {

            e.printStackTrace();

        }

    }



    //返回完整的json数据

    public String getJson(){

        return json;

    }



}

**Comment by mp2930696631** [comment]
兄弟，基础篇你又不看
https://mp.weixin.qq.com/s?__biz=MzU3MzIzODAzMw==&mid=2247483884&idx=1&sn=2be8dbebee41fb9989eade89db727107&chksm=fcc5ff92cbb27684e182bb05af722d5982e46f4905d824d19801ea04c24951cab871605792b0&token=106503137&lang=zh_CN#rd
到这里来提个issue态度还这么差，
代码是免费提供给你的，csdn里面的是测试数据，又不是强迫你下载，你自己要懒，不想自己组建测试数据，你又不想付费，你想上天不成
这些代码全是按原始工程结构上传的，自己不从头看教程，只想git clone一把然后项目就自己跑起来？？？
